### ISSUE TITLE
NPM install heavy af -- consider cutting unnecessary dependencies

### ISSUE THREAD

**Issue by robertDurst** [robertDurst/blockandjerrys#115]

**Comment by taariq** [comment]
Recommend you guys try yarn?

**Comment by robertDurst** [comment]
@tangsauce is the yarn guy. We have yarn right?

**Comment by tangsauce** [comment]
Yeah, but we have a few packages we aren't using that could be `yarn remove`d. Need consensus first on which ones aren't being used.
